trigger:
- master

resources:
  repositories:
  - repository: SampleMvcWebApp # https://github.com/JonPSmith/SampleMvcWebApp.git
    type: github
    #You will need to change or match this endpoint configuration
    endpoint: GitHubService
    name: JonPSmith/SampleMvcWebApp

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: struts2-rce
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: NexusIqPipelineTask@1
  inputs:
    #You will need to change or match this nexusIqService configuration
    nexusIqService: 'NexusIQService'
    applicationId: 'struts2-rce'
    stage: 'Build'
    scanTargets: '**/*'
