# Maven

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'install'
- task: NexusIqPipelineTask@1
  inputs:
    #You will need to change or match this nexusIqService configuration
    nexusIqService: 'NexusIQ'
    applicationId: 'struts2-rce'
    stage: 'Build'
    scanTargets: '**/*'
